/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type EnumDemo = 'red' | 'green' | 'blue';

export interface JobDemo {
  businessName: string;
  jobTitle: string;
}

/**
 * A list of People
 */
export type PeopleDemo = PersonDemo[];

/**
 * PersonDemo1
 */
export interface PersonDemo {
  firstName: string;
  job?: JobDemo;
  /**
   * Last Name
   */
  lastName: string;
  wallet?: WalletDemo;
}

export interface WalletDemo {
  /**
   * Number Property
   */
  [x: string]: number;
  eur: number;
  usd: number;
}
